In [65]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# Running Code

In .py file, `shift + enter` to run one line of code or the selected lines of code

  * It will run the code and print the output in the console
In Jupyter notebook, you click ![](img/run%20button.png) to run whole code chunk, or click ![](img/runbyline.png) to run line by line.

To have an interactive window, in command palette, type `> Jupyter: Create Interactive Window` 

# 1 Python Module

Consider the following module importation example:

In [48]:
import pandas as pd
import os
import matplotlib as mpl
import numpy as np

> make sure you have the module installed in your computer at the right Python environment. 
> At **Command palette** (Ctrl+Shift+P or Cmd+Shift+P in Mac) select **> Python: Create Terminal** to open a terminal that is using the right Python environment (which is `.venv` ) and install the module using `pip install <module-name>`.
> 
> ```bash
> pip install pandas matpotlib numpy
> ```



## 1.1 What a module offers

Once imported you an use the alias after `as` to access module functions. For example, the `numpy` module is imported with the alias `np` and the function `array()` is called using `np.array()`.


## 1.2 VSCode intellisence type of completion

  * [icon meanings](https://code.visualstudio.com/docs/editor/intellisense#_types-of-completions)

![](img/intellisense.png)



## 1.3 Frequently used functions

Sometimes there is a function you used often and you don't want to write the module name every time you call the function. You can import the function directly using the second method. For example, the `array()` function from the `numpy` module:


In [22]:
from numpy import array # usage array([1,2,3])
from numpy import array as arr # usage arr([1,2,3])

## 1.4 Module file structure  

A module is basically a collection of .py files that sits under the folder of the module name. For example, the `numpy` module sits at `.venv/lib/python3.11/site-packages/numpy` folder. 

```python
import numpy ...
from numpy ...
```

Means go to a module folder called `numpy` and do `...`. If the functions you want sits under a subfoler, say `numpy.random`, you can do:

```python
import numpy.random ...
from numpy.random ...
```

# 2 Data types

## 2.1 Python Data Types

  * [Python Data Types](https://www.w3schools.com/python/python_datatypes.asp)


In [22]:
# primitive data types
_string = "Hello World"
_integer = 1  
_float = 1.0  
_boolean = True # of False
_none = None # for a missig value

# collection data types
_range = range(5) # 0, 1, 2, 3, 4
print(_range)
_list = ["apple", 1, True]
_tuple = ("apple", 1, True)
_set = {"apple", "orage", "banana"}
_dictionary = {
    "name": "John", 
    "age": 36}  # "name": "John" is a key-value pair where key is "name"

range(0, 5)



## 2.2 Mutability and Immutability

Consider the following code:

```
a = some value
b = a
b = other value
```

  * `a = some value` will have computer find a memory space and passed its **location** back to `a`. Therefore, later when we `print(a)`. Computer will use that **location address** to read the value stored.  
  * At the second line, `b` is created and `a` will pass some information regarding `b`'s representing value. There are two possible passing methods:  
    * passing the **memory location**; or just
    * read the value and passs **just the value** 
```
# if a is immutable
b = other value # a is still some value

# if a is mutable
b = other value # a becomes other value
```

### a. Primitives are immutable
All **primitive types** are immutable. They are single value data types. 

  * `int`: `a = 2`
  * `float`: `a = 2.0`
  * `bool`: `a = True`
  * `str`: `a = "Hello World"`
  * `None`: `a = None` for missing value

### b. Most collections are mutable

Ｆor non-primitive types (i.e. collections of values), they are mostly mutable. 

  * `list`: `a = [1, 2, 3]`
  * `dict` (dictionary): `a = {"a": 1, "b": 2, "c": 3}`
  * `set`: `a = {1, 2, 3}`


### c. Collections with unchangeable values are immutable

  * `tuple`: `a = (1, 2, 3)`
  * `frozenset`: `a = frozenset({1, 2, 3})`

You can also create tuple by using `a = 1, 2, 3` without the brackets.

In [27]:
a = [1, 2, 3]
b = (1, 2, 3)

a[0] = 5 

b[0] = 5 # error. Unchangeable - immutable

TypeError: 'tuple' object does not support item assignment

# 3. List and dictionary

The most commonly used collective data types are `list` and `dict` -- both are mutable.  

* Okay to change their values.  
* Must use `.copy()` to make a copy of the values. (Using `=` to make a copy is NO NO.)

## 3.1 Change values

In [ ]:
list_example = [1, 2, 3, 4, 5]
dict_example = {"name": "John", "age": 36, "birthday": "01/01/1985"}

# change values
list_example[0] = 10
dict_example["name"] = "Jane"
print(list_example)
print(dict_example)

# delete values
del list_example[4]
del dict_example["birthday"]
print(list_example)
print(dict_example)

# add values
list_example.append(6) # add 6 to the end of the list
list_example.insert(0, 7) # add 4 to the beginning of the list
dict_example["birthday"] = "01/01/1985"
print(list_example)
print(dict_example)

[10, 2, 3, 4, 5]
{'name': 'Jane', 'age': 36, 'birthday': '01/01/1985'}
[10, 2, 3, 4]
{'name': 'Jane', 'age': 36}
[7, 10, 2, 3, 4, 6]
{'name': 'Jane', 'age': 36, 'birthday': '01/01/1985'}


## 3.2 Make a copy

In [43]:
list_example_copy = list_example.copy()
dict_example_copy = dict_example.copy()

list_example_copy[0] = 20
dict_example_copy["name"] = "Gary"

print(list_example)
print(dict_example)

[7, 10, 2, 3, 4, 6]
{'name': 'Jane', 'age': 36, 'birthday': '01/01/1985'}


([7, 10, 2, 3, 4, 6], {'name': 'Jane', 'age': 36, 'birthday': '01/01/1985'})

#  4. Numpy Array

List `[]` applies to a collection of data even if they are of different types. Since list can not be used to do math, even if all the values in a list are numbers, you can not do math with them.

Numpy array is a collection of data that are of the same type. It is a data type that is designed for math.

In [1]:
import numpy as np

In [13]:
x = np.ones(3)            # Vector of three ones
y = np.array((2, 4, 6))   # Converts tuple (2, 4, 6) into a NumPy array
x, y

(array([1., 1., 1.]), array([2, 4, 6]))

In [16]:
print(x + y)                    # Add (element-by-element)
print(x * y)                  # Multiply (element-by-element)
print(x @ y)                  # Dot product

[3. 5. 7.]
[2. 4. 6.]
12.0


In [7]:
A = np.array(
    ((1, 2),
     (3, 4))
     )
I = np.identity(3)
ones = np.ones((3, 2))

A, I, ones

(array([[1, 2],
        [3, 4]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 1.],
        [1., 1.],
        [1., 1.]]))

In [23]:
# transpose
A.T

# inverse
np.linalg.inv(A)


array([[1, 3],
       [2, 4]])

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

> Try to import just `inv` 

# 5. Data frame

Data frame is a collection of data that are of different types. It is a data type that is designed for data analysis.

To create a data frame, you need to import the `pandas` module.


In [24]:
import pandas as pd

# create data frame
df = pd.DataFrame({
    "name": ["John", "Jane", "Mary"],
    "age": [36, 24, 30],
    "birthday": ["01/01/1985", "01/01/1997", "01/01/1991"]
})

df

name  age    birthday
0  John   36  01/01/1985
1  Jane   24  01/01/1997
2  Mary   30  01/01/1991

In [31]:
# retrieve data
df["name"] # retrieve column "name"
# retrieve a row
df.iloc[0] # retrieve row 0

# retrieve multiple rows
df.iloc[[0, 2]] # retrieve row 0 and 2

0    John
1    Jane
2    Mary
Name: name, dtype: object

name              John
age                 36
birthday    01/01/1985
Name: 0, dtype: object

name  age    birthday
0  John   36  01/01/1985
2  Mary   30  01/01/1991

name  age    birthday
0  John   36  01/01/1985
1  Jane   24  01/01/1997

## Sequential retrerival

In Python you can retreive sequence of values from a list, tuple, or string using `[:]`. 

  * `[:]` is used to retrieve a sequence of values.
  

In [36]:
list_example = [2, 4, 8, 15, 16, 23, 42]

list_example[0:2] # retrieve element 0 and 1


[2, 4]

> sequential retrieval's end index is exclusive.

In [37]:
list_example[-1] # retrieve last element
list_example[0:6:2] # retrieve element 0, 2, 4

42

The same method can be used in `DataFrame.iloc[]` to retrieve a sequence of rows or columns.


In [ ]:
df.iloc[0:2] # retrieve row 0 and 1
df.iloc[0:2, 0:2] # retrieve row 0 and 1, column 0 and 1

name  age    birthday
0  John   36  01/01/1985
1  Jane   24  01/01/1997

name  age
0  John   36
1  Jane   24

# 6. Import files

## 6.1 JSON file

JSON file is the most common format to store data and exchange data between different systems. No matter what programming language you use, you can easily import a JSON file into your program.

To import a JSON file in Python, you can use the `json` module, which is a part of the standard library. Here is an example:

```python
import json

with open('path_to_your_file.json') as f:
    data = json.load(f)

# Now 'data' holds the content of your JSON file
```
In this code, 

- First, we import the `json` module.
- We use the built-in `open()` function to open the file. 
- The `'path_to_your_file.json'` should be replaced with the path to your JSON file. 
- We use the `json.load()` function to load the JSON file into the `data` variable. 

After this script is run, `data` will hold the contents of the JSON file as a Python object. If the JSON file contains a JSON object, `data` will be a dictionary. If the JSON file contains a JSON array, `data` will be a list.

Download [foodPandaMenu_a0ab.json](https://raw.githubusercontent.com/tpemartin/112-2-programming-for-economic-modeling/main/data/foodpandaMenu_a0ab.json) to your `root/data` folder. 

## 6.2 File Path


In [ ]:
# import json file
import json

with open('../data/foodpandaMenu_a0ab.json') as f:
    dd = json.load(f)

print(dd)

{'id': 28673, 'code': 'a0ab', 'accepts_instructions': True, 'address': '(△) 基隆市安樂區基金一路116-3號', 'address_line2': '', 'budget': 2, 'chain': {'code': '', 'name': '', 'main_vendor_code': '', 'url_key': ''}, 'city': {'name': 'Keelung City'}, 'cuisines': [{'id': 1227, 'name': '炒飯', 'url_key': 'chao-fan', 'main': False}, {'id': 201, 'name': '麵食', 'url_key': 'mian-shi', 'main': False}, {'id': 248, 'name': '台式', 'url_key': 'tai-shi', 'main': True}], 'custom_location_url': '', 'customer_type': 'all', 'delivery_box': '', 'delivery_fee_type': 'amount', 'description': '', 'distance': 0.929286742989499, 'food_characteristics': [{'id': 55, 'name': '<店內價>', 'is_halal': False, 'is_vegetarian': False}], 'has_delivery_provider': True, 'hero_image': 'https://images.deliveryhero.io/image/fd-tw/LH/a0ab-hero.jpg', 'hero_listing_image': 'https://images.deliveryhero.io/image/fd-tw/LH/a0ab-listing.jpg', 'is_new_until': '2019-11-04T00:00:00Z', 'premium_position': 0, 'latitude': 25.1401844, 'logo': '', 'longitude


In programming, a file has two types of paths:  

- **Relative path**: relative to the current working directory.  
- **Absolute path**: the full path to the file.  

For example, suppose you have a file with the absolute path `C:\Users\username\Documents\data.json`. If the current working directory is `C:\Users\username\Documents`, then the relative path to the file `data.json` is `data.json`. If the current working directory is `C:\Users\username`, then the relative path to the file `data.json` is `Documents\data.json`.

In Python, you can get the current working directory using the `os` module (`os` module comes with Python installation. No need to install it first.). Here is an example:


In [ ]:
import os

cwd = os.getcwd()
print(cwd)

In my computer, I have the following folder structure:

```
root
├── data
│   ├── ...
│   └── w_2023-02-07.json
└── ipynb
    └── week-2.ipynb
```

  * `root` means the project root folder. 

My `week-2.ipynb` working directory is `ipynb` folder. To access the file `w_2023-02-07.json` in `data` folder, we can use `..` which means the parent folder of the current working directory. 

Hence we can use `../data/w_2023-02-07.json` to access the file `w_2023-02-07.json` in `data` folder.



> **Note**:  
> 1. All the discussion regarding relative path here is based on that you have set up a Python environment and linked your Jupyter Notebook to the Python environment correctly.
> 2. If you are running .py file, the current working directory is the folder where project root is. (This means if data folder's relative paths are the same across developers, the code line to access that file will be the same across developers regardless of where they saved their scripts inside the project root.)

#### Exercise


Create two files named `test.py` in different folders of your root with the following code:

```python
import os

cwd = os.getcwd()
print(cwd)
```

Verify that they both have the same `cwd`, then import the same json file inside your project folder

## 6.3 CSV file



In [4]:

import pandas as pd

df = pd.read_csv("https://raw.githubusercontent.com/tpemartin/"\
                 "github-data/master/Cornwell%20and%20Rupert.csv")

In Mac some people may encouter SSL: CERTIFICATE_VERIFY_FAILED error. To solve this problem, look for `Install Certificates.command` in your Python folder. Its path may look like 
`/Applications/Python 3.11/Install Certificates.command`, then run

```bash
sudo /Applications/Python\ 3.11/Install\ Certificates.command
```
  * `\ ` escape space in bash

# Download through command

In [1]:
import requests

url = 'https://raw.githubusercontent.com/tpemartin/'\
    '112-2-programming-for-economic-modeling/main/data/foodpandaMenu_a0ab.json'  # URL of the file to download
response = requests.get(url)

# Ensure the request was successful
response.raise_for_status()

# Open the file in write mode
with open('foodpandaMenu_a0ab.json', 'wb') as file:
    file.write(response.content)


### File modes:  



In Python, the `open` function is used to open a file and it takes a mode parameter. Here are the available modes:

1. `'r'`: Read mode which is used when the file is only being read. This is the default mode if no mode is specified.

2. `'w'`: Write mode for rewriting the contents of a file.

3. `'x'`: Exclusive creation mode for creating a new file. If the file already exists, the operation fails.

4. `'a'`: Append mode for appending new content to the end of the file.

5. `'b'`: Binary mode for reading or writing binary data.

6. `'t'`: Text mode for reading or writing string data. This is the default mode if no mode is specified.

7. `'+'`: Updating mode for reading and writing to the same file.

These modes can also be combined. For example:

- `'rb'`: Read in binary mode.
- `'wt'`: Write in text mode.
- `'a+'`: Append and read.
- `'r+b'`: Read and write in binary mode.
  
Note: `'b'`, `'t'`, and `'+'` can be appended to `'r'`, `'w'`, `'x'`, and `'a'`.

# 7. Saving your work

In Python variables can be saved in a file using the `pickle` module. Here is an example:


In [ ]:
import pickle  

# Save a dictionary into a pickle file.  
favorite_color = { "lion": "yellow", "kitty": "red" }  
with open( "save.p", "wb" ) as f:  
    pickle.dump(favorite_color, f)   


# To load the dictionary back from the pickle file.  
with open( "save.p", "rb" ) as f:
    favorite_color = pickle.load(f)


  * Notice where `save.p` is saved in your computer (depending on you run it inside .ipynb or .py).   
  * `pickle` module is for Python developers only. It is not for sharing data with other non-python developers.

If you are to share your saved variables with non-Python users, you can use the `json` module to save your variables in a JSON file. Here is an example:

In [ ]:
import json

with open('save.json', 'w') as f:
    json.dump(favorite_color, f)
